export enum RoleEnum {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_AGENT = 'ROLE_AGENT',
  ROLE_AGENT_CHECKIN = 'ROLE_AGENT_CHECKIN',
  ROLE_AGENT_TEST = 'ROLE_AGENT_TEST',
  ROLE_AGENT_PAY = 'ROLE_AGENT_PAY',
  ROLE_AGENT_INJECT = 'ROLE_AGENT_INJECT',
  ROLE_AGENT_MONITOR = 'ROLE_AGENT_MONITOR',
  ROLE_GUEST = 'ROLE_GUEST',
}
