version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/vrms-web:$CIRCLE_BRANCH .
      - run: docker push $DOCKERHUB_USERNAME/vrms-web:$CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
