export enum VcnProfileStatusEnum {
  CREATED = 'CREATED',
  CHECKED_IN = 'CHECKED_IN',
  TESTED_PASSED = 'TESTED_PASSED',
  TESTED_FAILED = 'TESTED_FAILED',
  PAID = 'PAID',
  INJECTED = 'INJECTED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}
